-- 1. Drop check constraint and default value on wallet id to support multiple accounts
alter table wallet drop constraint if exists wallet_id_check;
alter table wallet alter column id drop default;

-- 2. Enable auto-incrementing identity on wallet id column
alter table wallet alter column id add generated by default as identity;

-- 3. Add name column to wallets
alter table wallet add column if not exists name text not null default 'Main Wallet';

-- 4. Add unique constraint to prevent duplicate account names per user
alter table wallet add constraint wallet_name_unique unique (user_id, name);

-- 5. Add wallet_id column to transactions referencing the wallet table
alter table transactions add column if not exists wallet_id int references wallet(id) on delete cascade;

-- 6. Link existing transactions to the default 'Main Wallet' (id = 1)
update transactions set wallet_id = 1 where wallet_id is null;

-- 7. Enforce NOT NULL on the transaction wallet_id column
alter table transactions alter column wallet_id set not null;

-- 8. Seed some popular wallets (Maribank, Maya) for immediate switching
insert into wallet (id, name, balance)
values 
  (2, 'Maribank', 0.00),
  (3, 'Maya', 0.00),
  (4, 'Gcash', 0.00)
on conflict (id) do nothing;

-- 9. Sync the identity sequence generator with existing IDs
select setval(pg_get_serial_sequence('wallet', 'id'), coalesce(max(id), 1)) from wallet;
