-- Run this in the Supabase SQL Editor (Dashboard → SQL → New query)

-- 1. Wallet Table Setup
create table if not exists wallet (
  id int primary key generated by default as identity,
  name text not null default 'Main Wallet',
  balance numeric(12, 2) not null default 0,
  user_id uuid references auth.users(id) default auth.uid(),
  updated_at timestamptz not null default now(),
  constraint wallet_name_unique unique (name)
);

-- Seed initial wallets
insert into wallet (id, name, balance)
values 
  (1, 'Main Wallet', 0.00),
  (2, 'Maribank', 0.00),
  (3, 'Maya', 0.00),
  (4, 'Gcash', 0.00)
on conflict (id) do nothing;

-- Sync the identity sequence generator
select setval(pg_get_serial_sequence('wallet', 'id'), coalesce(max(id), 1)) from wallet;

-- 2. Transactions Table Setup
create table if not exists transactions (
  id uuid primary key default gen_random_uuid(),
  amount numeric(12, 2) not null,
  description text not null default '',
  category text not null check (category in ('Food', 'Bills', 'Transport', 'Income', 'Other', 'Bank Transfer', 'Shopping', 'Travel', 'Education', 'Entertainment', 'Health')),
  date date not null default current_date,
  created_at timestamptz not null default now(),
  wallet_id int not null references wallet(id) on delete cascade,
  user_id uuid references auth.users(id) default auth.uid()
);

-- 3. Upcoming Expenses Table Setup
create table if not exists upcoming_expenses (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  details text not null default '',
  amount numeric(12, 2) not null,
  date date,
  wallet_id int references wallet(id) on delete cascade,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id) default auth.uid()
);

-- 4. Enable Row Level Security (RLS)
alter table wallet enable row level security;
alter table transactions enable row level security;
alter table upcoming_expenses enable row level security;

-- 5. Wallet Policies
create policy "Allow users to read their own wallet"
  on wallet for select using (auth.uid() = user_id);

create policy "Allow users to insert their own wallet"
  on wallet for insert with check (auth.uid() = user_id);

create policy "Allow users to update their own wallet"
  on wallet for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Allow users to delete their own wallet"
  on wallet for delete using (auth.uid() = user_id);

-- 6. Transactions Policies (Restricted by User)
create policy "Allow users to read their own transactions"
  on transactions for select using (auth.uid() = user_id);

create policy "Allow users to insert their own transactions"
  on transactions for insert with check (auth.uid() = user_id);

create policy "Allow users to update their own transactions"
  on transactions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Allow users to delete their own transactions"
  on transactions for delete using (auth.uid() = user_id);

-- 7. Upcoming Expenses Policies (Restricted by User)
create policy "Allow users to read their own upcoming_expenses"
  on upcoming_expenses for select using (auth.uid() = user_id);

create policy "Allow users to insert their own upcoming_expenses"
  on upcoming_expenses for insert with check (auth.uid() = user_id);

create policy "Allow users to update their own upcoming_expenses"
  on upcoming_expenses for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Allow users to delete their own upcoming_expenses"
  on upcoming_expenses for delete using (auth.uid() = user_id);
